# Site wide configuration

title:            Palina Tolmach
locale:           en_US
url:              http://palinatolma.ch

name: Palina Tolmach
description: Palina Tolmach's homepage.

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: assets/css/_sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Palina Tolmach
  avatar: profile.png
  position: "PhD Candidate"
  affiliation-one: "School of Computer Science and Engineering (SCSE)\nNanyang Technological University (NTU)"
  affiliation-two: "Institute of High Performance Computing (IHPC)\nAgency for Science, Technology and Research (A*STAR)"
  contact: "Address: Block N4-B2C-06\n50 Nanyang Avenue, Singapore 639798\nPhone: +65 842 606 82"
  email: palina001@e.ntu.edu.sg
  twitter: palinatolmach
  scholar: https://scholar.google.com/citations?user=KmjceS0AAAAJ&hl=en
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
    scholar: 
  bing-verify: 
  github: polinatolmach
  linkedin: palina-tolmach-70238912a
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md",vendor]